"""Initial migration

Revision ID: 1501d1f09f1e
Revises: 
Create Date: 2026-08-25 11:34:05.752607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1501d1f09f1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
