"""Add user model

Revision ID: 554fac12adf2
Revises: 1501d1f09f1e
Create Date: 2026-08-27 20:13:25.699313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554fac12adf2'
down_revision = '1501d1f09f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
